### PR TITLE
Add GIN paper

### PR DESCRIPTION
**Pull request by JeanKaddour**
Thank you very much for creating this excellent repo! I wanted to suggest adding our recent work on vectorized treatments (e.g. graphs). Our estimator is based on a generalization of the Robinson decomposition and allows one to decompose causal effect estimation into separate, simpler optimization problems.

### CODE REVIEW

**Comment by jvpoulos** [comment]
Thanks for the contribution! I may later move this to the section on "heterogeneous treatment effects"  if you don't mind.

**Comment by JeanKaddour** [comment]
Thank you very much for accepting the PR.

I just had a look at both sections. I think you're right; our paper estimates CATEs, so the section HTE is better suited. However, this applies to most papers in the ITE section (if not all); they are effectively estimating CATEs/HTEs. By definition, ITEs are a counterfactual quantity, see e.g.
https://twitter.com/yudapearl/status/1284483401559314432?lang=en
https://drive.google.com/file/d/1exByH8TE8OSWCzAhUD1Ir_jDJ4U747t2/view

Maybe it's a good idea to merge them.

**Comment by jvpoulos** [comment]
The ITE/CATE distinction hadn't occurred to me... my view is similar to Uri in the twitter comments (https://twitter.com/ShalitUri/status/1284850926214434816?s=20).  In the former we are conditioning on all observed covariates and in the latter we are conditioning on certain covariates, like in sub-group analysis. 

We could make HTEs/CATEs a subsection of individualized treatment effects?

**Comment by JeanKaddour** [comment]
Sounds good to me! 👍

**Pull request merged**
